POST http://localhost:3000/api/v1/devices/node/control HTTP/1.1
content-type: application/json

{
    "gatewayId": "GW-4",
    "nodeId": "nodeCC29490B65F4",
    "action": "ON", 
    "mode": "MANUAL"
}
###